sonar.projectKey=GONZAORBAN_2DO-PARCIAL-ICS
sonar.organization=gonzaorban

sonar.sources=src
sonar.tests=tests,e2e
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**,dist/**,.next/**,.github/**
sonar.test.exclusions=e2e/**

sonar.sourceEncoding=UTF-8